apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: webserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web-nginx
  strategy:
    canary:
      canaryService: {{ .Chart.Name }}-canary
      stableService: {{ .Chart.Name }}-stable
      trafficRouting:
        nginx:
          stableIngress: {{ .Chart.Name }}-ingress
          additionalIngressAnnotations:
            canary-by-header: {{ .Values.canary.header.name }}
            canary-by-header-value: "{{ .Values.canary.header.value }}"
      steps:
      # we can not use set weight here since this option does not support traffic routing
#      - setWeight: 1
        # because we're using traffic routing we need to explicitly
        # set the replica counts needed to
      - setCanaryScale:
          replicas: {{ .Values.canaryReplicaCount }}
      - pause: {}
  rollbackWindow:
    revisions: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
