apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary-by-header: {{ .Values.canary.header.name }}
    nginx.ingress.kubernetes.io/canary-by-header-value: "{{ .Values.canary.header.value }}"
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          # Reference to a Service name, also specified in the Rollout spec.strategy.canary.stableService field
          service:
            name: {{ .Chart.Name }}-stable
            port: 
              number: 80